Repository forcedotcom/salesforcedx-templates, pull requests merged in 2020-01, with the labels that each got.

#64 Autointegrator config
  .github/autointegrator.yml
Labels: port:develop, port:pre-release, port:release

#68 Show correct default directory for project creation help
  README.md
  src/commands/force/project/create.ts
Labels: port:develop, port:pre-release

#72 sfdx force:project:create should not create a duplicate project in th…
  src/generators/projectGenerator.ts
  test/commands/project/create.test.ts
Labels: port:develop, port:pre-release

#75 Update default outputdir for all commands to '.'
  src/commands/force/analytics/template/create.ts
  src/commands/force/apex/class/create.ts
  src/commands/force/apex/trigger/create.ts
  src/commands/force/lightning/app/create.ts
  src/commands/force/lightning/component/create.ts
  src/commands/force/lightning/event/create.ts
  src/commands/force/lightning/interface/create.ts
  src/commands/force/lightning/test/create.ts
  src/commands/force/visualforce/component/create.ts
  src/commands/force/visualforce/page/create.ts
Labels: port:develop, port:pre-release

#76 Port #75 to develop and add missing analytics template command to develop branch
  messages/messages.json
  src/commands/force/analytics/template/create.ts
  src/commands/force/apex/class/create.ts
  src/commands/force/apex/trigger/create.ts
  src/commands/force/lightning/app/create.ts
  src/commands/force/lightning/component/create.ts
  src/commands/force/lightning/event/create.ts
  src/commands/force/lightning/interface/create.ts
  src/commands/force/lightning/test/create.ts
  src/commands/force/visualforce/component/create.ts
  src/commands/force/visualforce/page/create.ts
  src/generators/analyticsTemplateGenerator.ts
  src/templates/analytics/waveTemplates/DefaultAnalyticsTemplate/app-to-template-rules.json
  src/templates/analytics/waveTemplates/DefaultAnalyticsTemplate/dashboards/basicDashboard.json
  src/templates/analytics/waveTemplates/DefaultAnalyticsTemplate/folder.json
  src/templates/analytics/waveTemplates/DefaultAnalyticsTemplate/releaseNotes.html
  src/templates/analytics/waveTemplates/DefaultAnalyticsTemplate/template-info.json
  src/templates/analytics/waveTemplates/DefaultAnalyticsTemplate/template-to-app-rules.json
  src/templates/analytics/waveTemplates/DefaultAnalyticsTemplate/ui.json
  src/templates/analytics/waveTemplates/DefaultAnalyticsTemplate/variables.json
  test/commands/force/analytics/template/create.test.ts
Labels: port:pre-release
