Repository forcedotcom/salesforcedx-templates, pull requests merged in 2020-02, with the labels that each got.

#78 chore: merge release to master @W-7208018@
  messages/messages.json
  package.json
Labels: port:develop, port:pre-release

#80 Use shx in postpack
  package.json
Labels: port:develop, port:pre-release

#83 Windows build/test using CircleCI
  .circleci/config.yml
  .nycrc
  package.json
  scripts/remove-lib.js
Labels: port:develop, port:pre-release

#88 Enable code owners
  .github/CODEOWNERS
Labels: port:develop, port:pre-release, port:release

#87 force:analytics updates
  package.json
  src/templates/analytics/waveTemplates/DefaultAnalyticsTemplate/app-to-template-rules.json
  src/templates/analytics/waveTemplates/DefaultAnalyticsTemplate/dashboards/basicDashboard.json
  src/templates/analytics/waveTemplates/DefaultAnalyticsTemplate/folder.json
  src/templates/analytics/waveTemplates/DefaultAnalyticsTemplate/template-info.json
  src/templates/analytics/waveTemplates/DefaultAnalyticsTemplate/template-to-app-rules.json
  src/templates/analytics/waveTemplates/DefaultAnalyticsTemplate/ui.json
  src/templates/analytics/waveTemplates/DefaultAnalyticsTemplate/variables.json
  test/commands/force/analytics/template/create.test.ts
Labels: port:develop, port:pre-release, port:release

#96 added package.json to project (#42)
  src/generators/projectGenerator.ts
  src/templates/project/.eslintignore
  src/templates/project/.prettierignore
  src/templates/project/gitignore
  src/templates/project/package.json
  test/commands/project/create.test.ts
Labels: port:develop

#97 added package.json to project (#42)
  src/generators/projectGenerator.ts
  src/templates/project/.eslintignore
  src/templates/project/.prettierignore
  src/templates/project/gitignore
  src/templates/project/package.json
  test/commands/project/create.test.ts
Labels: port:develop, port:pre-release
